### ISSUE TITLE
Avoid unnecessary allocation in checking operator properties

### ISSUE THREAD

**Issue by djmitche** [json-e/json-e#397]
The `check_operator_properties` function allocates on every call, but in many cases that allocation is unnecessary.

**Comment by iwyatt** [comment]
I'll submit a PR for this once I have a tested solution I think works. I need to set up a test environment and haven't used a local .librc before. Once I figure that part out, should be straight forward.

**Comment by djmitche** [comment]
I'm curious what `.librc` is?

This should be testable with `cd rs; cargo test`.

**Comment by iwyatt** [comment]
Good question - that was a typo. I meant ` libjson_e.rlib` which is the compiled library I made when I was set up a separate local repo as a testing environment. I've since adopted `cargo test` per your suggestion and written a couple test cases in `render.rs`

I thought this was going to be straightforward using `.iter()`, but it turns out that `&BTreeMap<String, Value>` type is a bit inconvenient to work with. 

This has so far, led me to two solutions, neither of which I am confident save much from the current implementation memory allocation: `let mut unknown = Vec::new();` prior to the for loop.

I understand that avoiding the allocation could save a processing step and some memory. Which means any other solution should at least avoid allocating the same amount of memory in fewer code paths, if not all.

I think there may be a third solution which involves checking `iter().any()` and _only then_ allocating memory to variable to generate the error message. This has the down side of having more operating steps since it could involve iterating through the whole list twice. (I think that is (O(n*2), right?). It would have to be a REALLY big json-e template to make the additional processing time more valuable than using the incremental memory allocation for a temporary variable. I might be over-thinking all of this. 

Here are the two solutions I've tested:

**Solution 1:** 
```rust
    // solution 1: still creates a vector to be evaluated, and is filtered in-place, thus saving some memory, but still creating an empty vector which seems equivalent memory-wise to the original. 
    let unknown: Vec<String> = object.keys()
        .filter(|k| k.as_str() != operator)
        .filter(|k| !check(k))
        .map(|k| k.to_string())
        .collect();
    
    if unknown.len() > 0 {
        Err(template_error!(
            "{} has undefined properties: {}",
            operator,
            unknown.join(" ")
        ))?
    }
```

**Solution 2:**
``` rust
    // solution 2: this allocates in-place by overwriting object, but is that any better?
    // the intent was to .drain_filter() on `object` but that method isn't available for BTreeMaps
    let object: String = object.keys()
    .filter(|k| k.as_str() != operator)
    .filter(|k| !check(k))
    .map(|k| k.to_string())
    .fold(String::from(""), |acc, k| acc + " " + &k);

    if object.len() > 0 {
        Err(template_error!(
            "{} has undefined properties: {}",
            operator,
            object
        ))?
    }
```

I can take another look at this next week. =)

**Comment by djmitche** [comment]
Nice thinking! But I may have been too hasty in suggesting this bug. It turns out, [Vec::new()](https://nnethercote.github.io/perf-book/heap-allocations.html?highlight=borrow#vec-growth) doesn't allocate immediately -- only when a value is first put into the vector. I suspect I didn't know this when I created this issue!

I confirmed this with the [Compiler Explorer](https://godbolt.org/z/1oWvWcdrT):
```rust
pub fn main() {
    let mut x: Vec<u32> = Vec::new();

    if std::hint::black_box(true) {
        x.push(10);
    }
}
```

The "happy path" for `check_operator_properties` doesn't push anything to the vector, so I think it doesn't actually allocate anything.

**Comment by iwyatt** [comment]
Thanks for the feedback and I'm glad to see there is a way to diagnose the code efficiency. I don't know how to read assembly (I think that is the language I'm seeing post-compile, right?) but good to know that tool exists. I was wondering about memory profilers for Rust but examining the compiled code seems a more straightforward task.

**Comment by djmitche** [comment]
Yes, that's assembly. I certainly couldn't write it, but can usually puzzle out enough to learn what I needed to know.
