### ISSUE TITLE
Standardize the JSON-e templating language

### ISSUE THREAD

**Issue by jviotti** [json-e/json-e#446]
Hey there!

Are there any plans to attempt to standardize the JSON-e templating language? Doing so would encourage more adhering third-party implementations. 

For example, I'm particularly interested on a C++ implementation. While the language documentation is clear, I'm concerned the language itself might change without any versioning attached to it, rendering third party implementations suddenly incompatible.

**Comment by djmitche** [comment]
Hm, what would that look like?  The spec is pretty good but I think anyone from a language-standards background would find it lacking and ambiguous in some important spots.

**Comment by jviotti** [comment]
Clarity is in place. My concern is mostly versioning. There is no concept around versioning the JSON-e language itself (independently from its main implementations), and so there no guarantees that JSON-e will just change out of the sudden, rendering third-party implementations incompatible.

**Comment by djmitche** [comment]
At the moment, the language is versioned along with the implementations.  Which means that if there's an incompatible change, that would be a major version.  For example, version 4 introduced short-circuiting in || and &&.  Practically that's hardly a breaking change, since it only means previously-invalid templates are now valid, while results for all valid templates are unchanged.

I think a third-party implementation could advertise compatibility with a major version.  I'm not sure we can make a stronger guarantee than that, although we could make it clearer in the README.

Historically, the more common compatibility issues have not been a deliberate breaking change to the language, but a discovery that different implementations do something different in an edge case.  Once such a discovery is made, we technically have two JSON-e's, and need to break one of them (or document the behavior as undefined, but that's not a great solution).  I suppose having a third-party implementation would be a bit nicer because it would be an easier decision which version "wins" -- if the C++ impementation does something different from the Go implementation, the C++ implementation is wrong :)

I think compatibility would be more of an issue for consumers of the language (that is, people writing JSON-e templates).  If a C++ implementation is correct for, say, JSON-e 4.x, then it's correct, and whether that consumer is using the third-party C++ implementation or a first-party Rust implementation, a 5.x is going to present compatibility problems.

The final datapoint I'd add is that at Mozilla, a major consumer of this language, JSON-e is used in a number of places and is at a point where it would be impossible to find all uses of the language and migrate them over a breaking change.  So, I'd expect things to be pretty stable from here on out.

So:
 * Write your implementation!  Sounds like a fun project!
 * Especially if you're willing to maintain it, we'd welcome that C++ implementation in this repo.
 * If you choose to make it external, indicate that it implements JSON-e 4.x, and keep an eye out for a 5.x (that may never come).

**Comment by jviotti** [comment]
@djmitche Thanks a lot for the encouraging response!

> Which means that if there's an incompatible change, that would be a major version. 

That makes sense. I wonder if that sentence is worth documenting very clearly on the README.

> if the C++ impementation does something different from the Go implementation, the C++ implementation is wrong 

If I do end up doing this at some point in the future, would there be interest on maintaining a 100% JSON-based language-independent test suite all implementations can share? Something like https://github.com/json-schema-org/json-schema-spec for JSON Schema?

**Comment by djmitche** [comment]
I think `specification.yaml` is close to that?

**Comment by jviotti** [comment]
Ah, I had totally missed that file. I guess the name is a bit misleading. Thanks for all the guidance. Feel free to close this issue if you want!

**Comment by djmitche** [comment]
I'll keep it open to update the README.  But, yeah, that's the "definitive" language reference.  The bit that isn't finished is related to error messages -- we made an effort to standardize them but didn't finish.  Still, all supported languages do the same thing for all of those 1000+ (if I remember correctly) cases.

If you do embark on a C++ implementation, and it's not in this repo, please feel welcome to contribute additional cases to `specification.yaml`, either addressing a corner case you discover in your implementation that was otherwise ambiguous, or (worse, but not unexpected) identifying a case where the existing implementations differ.
