### ISSUE TITLE
json-e.js.org $let documentation missing $let in templates

### ISSUE THREAD

**Issue by Zacho2** [json-e/json-e#461]
When I go to https://json-e.js.org/operators.html#let, the $let operator seems to be missing from all the templates. Looking at the markdown file source that I assume is being hosted, the $let operator has been in all templates for ~two years https://github.com/json-e/json-e/blob/4c9cd1235cbe91ac0d34d351d2a0469c97197b0c/docs/src/operators.md#let. This left me scratching my head. I ended up using https://github.com/json-e/json-e/blob/main/specification.yml#L679 for $let examples.

**Comment by djmitche** [comment]
I think this is because those are the only examples taking advantage of the ability to put arbitrary newlines in JSON within YAML. The JS interpreting the YAML assumes either

```yaml
template: [some, template]
```
or
```yaml
template:
  [some, template]
```
but not
```yaml
template: [some,
  template]
```
and that's where it's getting confused. It's probably best to just make the JS handle this situation correctly.

Do you want to take a try at that (it's in `docs/jsone.js`)?
