### ISSUE TITLE
Using json-e to Generate JSON stanzas

### ISSUE THREAD

**Issue by kwhitehouse** [json-e/json-e#532]
# Goal
We'd like to be able to generate multiple JSON stanzas based on user input.

We're expecting that we could pass in an empty context and generate the result shown below. We came up with two ideas for how we could implement this via json-e, and would love input on whether one of these options feels like a better solution. We'd love to open a PR to propose the support once we hear what you folks think would make sense!

### Context
```
{}
```

### Result
```
[
   { "hello0" :  11 }, 
   { "hello1" :  12 }
]
```

## Option A
Introduce for-loops to json-e.

### Template
```
$for: { from: 10, until: 11}
each(x, i): { 'hello${i}': { $eval: 'x + 1' } }
```

## Option B
Introduce two built-in functions -- `range` and `list` -- and make use of existing operator `map` and `each`.

### Template
```
$map: {$eval: 'list(range(10, 11))'}
each(x, i): { 'hello${i}': { $eval: 'x + 1' } }
```

**Comment by djmitche** [comment]
There is some history for this idea in #250.

One of the key requirement of JSON-e is

> It also disallows unbounded iteration, so any JSON-e rendering operation will finish in finite time.

So an arbitrary looping construct would not be suitable. Neither option here is "unbounded" so does not violate this requirement. In #250 and #305 we also consider existing cases where time and memory complexity is highly exponential with respect to the input size, which might lead to denial of service when evaluating untrusted inputs. I suspect that the fix is this sort of "sandboxing" (timeout and maximum memory usage) rather than trying to limit time and space usage to some function of input size.

All of which is to say, I think we should add this to the language.

Option A: I like this form, although I think it's a little surprising for a `for` loop to create an array -- I don't know of another language where that's the case. But JSON-e doesn't have side-effects, so I suppose it couldn't do anything else! The syntax might tempt users to write `{from: 10, until: 20}` in hopes of getting an array `[10, ..,19]`, but hopefully it's clear enough why that doesn't work. In terms of implementation, the `$for` operator doesn't need to allocate an array of integers, so for example a filtering expression like `{$for: { from: 0, until: 1000000 }, each(x): {$if: "f(x) == 7", then: "seven"}}` would use bounded space.

Option B: I'm unclear why this would need two new functions. And, one issue with the pair of functions is the return type. For example, what is `{$eval: "range(10, 11)"}`? Currently types in JSON-e are JSON's types plus functions, and adding an additional "range" type would be a pretty disruptive change. This approach also generates a big array of integers (presumably the return value of `list(..)` is an array) which may not be necessary. Overall, I don't see any advantage here over Option A.

I'm curious what others think! @gregsdennis? @pmoore?

**Comment by gregsdennis** [comment]
In .Net there is a technology called LINQ.  Essentially, it's a set of functions that build what they call "deferred execution" queries.  These queries exist unactualized until they're iterated.

For example,

```c#
var array = [1,2,3,4,5];
var query = array.Where(x => x > 3).Select(x => x * 2);
var result = query.ToArray();
```

The `query` variable isn't an allocated array.  (There _is_ some allocation for the query, but it's not an array of the results.)  The array isn't allocated until the query is evaluated with the `.ToArray()` method.

In this way, having separate `list()` and `range()` methods makes sense.  Something like

```
list(range(10,20))
```

could be written like this in C#:

```c#
var result = Enumerable.Range(10,11).ToList();
```

(`Enumerable.Range()` takes a start and a count rather than a start and an end, but you get the picture.)

Here, `Enumerable.Range()` doesn't actually allocate the array of numbers; it merely represents the idea of that range.  The `.ToList()` method executes the query and allocates a `List<int>` to store the results.

An implementation could certainly implement a `range()` function to do this sort of thing, but I don't think that it's the job of JSON-e to specify this behavior.  Because of this, I agree that the `list()` function is somewhat superfluous; `range()` is sufficient here.

Regarding the options presented, I believe that `range()` fits the declarative nature of JSON-e better than an iterative `$for` operator does.  I'm in favor of `range()` as a function.

**Comment by djmitche** [comment]
The "unactualized" value is what Rust, Python, and other languages call an "iterator", and is roughly what I was referring to as "additional "range" type" in [my earlier comment](https://github.com/json-e/json-e/issues/532#issuecomment-2366770109). I'd prefer not to introduce a new type like that to the language.

If `range` returns an array, as you suggest, then something like
```
{$for: {$eval: "range(0, 1000000)"}, each(x): {$eval: "x * x"}}
```
would allocate two arrays (one of integers 0 to 1,000,000, and one of squares 0 to 1,000,000<sup>2</sup>).

I guess the questions to ask are
 * is that cost worthwhile for the more declarative nature of `range`?
 * would `range` be useful in other contexts?

**Comment by gregsdennis** [comment]
That would require having both `$for` _and_ `range()`.  Are we not discussing the adoption of _one_ of these?  I can't think why you'd need both.

**Comment by kwhitehouse** [comment]
Thanks Greg and Dennis! This is not yet ready for a formal review, but if you folks have time to take a peek at https://github.com/json-e/json-e/pull/534, it'd be great to get your feedback to see if it resonates with your expectations. 

The output simply makes use of **Python's** [`range`](https://docs.python.org/3/library/functions.html#func-range) built-in. 
* **Rust** - It looks like a similar function exists in Rust, https://doc.rust-lang.org/std/ops/struct.Range.html, however it'd have to be combined with [`step_by`](https://stackoverflow.com/questions/27893223/how-do-i-iterate-over-a-range-with-a-custom-step) to achieve feature parity with the Python built-in.
* **Javascript** - [This stackoverflow](https://stackoverflow.com/questions/3895478/does-javascript-have-a-method-like-range-to-generate-a-range-within-the-supp) has a few nice options for how we might implement range.

**Comment by djmitche** [comment]
> That would require having both `$for` _and_ `range()`. Are we not discussing the adoption of _one_ of these? I can't think why you'd need both. (I think `$map` would do what you're saying above.)

You're right - I should have used `$map` and not `$for` in my example above.
 
> Regarding your point of multiple allocations, I think at some point you have to leave the responsibility of managing that to the user. Your responsibility is to document the behavior so that your users can make educated decisions.

Sure, but if there's no way for the user to manage it then it's just a well-documented bug! But, nothing in JSON-e is very efficient in terms of allocations, so I think it's fine.

> The output simply makes use of **Python's** [`range`](https://docs.python.org/3/library/functions.html#func-range) built-in.

You'll want to be careful here not to accidentally inherit any behaviors of the Python function that might be different in other languages. Documenting and testing the edge cases will be important -- start > end, start == end, step = 0, step < 0, step not evenly dividing (end - start), and so on. We've gotten in trouble with earlier iterations of JSON-e when we've under-specified things and different implementations have had different behavior.

>     * **Rust** - It looks like a similar function exists in Rust, https://doc.rust-lang.org/std/ops/struct.Range.html, however it'd have to be combined with [`step_by`](https://stackoverflow.com/questions/27893223/how-do-i-iterate-over-a-range-with-a-custom-step) to achieve feature parity with the Python built-in.

This sounds like a good idea. Something like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=50d8769a05a19059d60d81523277c67e). I tried generating the assembly for this, but in release mode it's very hard to get Rust not to just pre-calculate the whole vector!

**Comment by kwhitehouse** [comment]
Thanks all for the support in adding this feature! Closing this issue.
